### ISSUE TITLE
Config permissions issue

### ISSUE THREAD

**Issue by M1SM4TCH** [Prunt/RestrictedCreative#17]
When the player activate gamemode, does not receive the permissions specified in the config.
https://hastebin.com/ifuretefeg.php

RestrictedCreative 1.12.7
PermissionsEx v1.23.4
Paperspigot 1.8.8

**Comment by Prunt** [comment]
Any errors in the config? How did you check if the permissions were given/taken?

RestrictedCreative doesn't link directly to PEX or other permission handling plugins, but rather Bukkit's own permissions API, that's why it won't show up when checking it with PEX commands. The given permissions should, however, work correctly when tested.

**Comment by M1SM4TCH** [comment]
I believe there is no error in config.
I tested with WorldGuard, FAWE, and WorldEdit permissions (to only release them in the gamemode). And didn't work.

**Comment by Prunt** [comment]
Oh, sorry, I meant console, not config. I'll test it myself and let you know.

**Comment by M1SM4TCH** [comment]
Okay, I'll wait for it

**Comment by Prunt** [comment]
New version is out, give it a go and let me know if it works.
