### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by EvilSlime** [Prunt/RestrictedCreative#22]
I know why it kept sending me the console Alert.

database:
  type: SQLite
  username: root
  password: ''
  host: localhost
  port: 3306
  database: rc_database
  table: rc_table

You have the data base automaticly on SQLite not on MySQL

**Comment by EvilSlime** [comment]
I don't know how that stuff works.

**Comment by EvilSlime** [comment]
You have this by default can you change default to MySQL?

**Comment by Prunt** [comment]
I have "SQLite" set as default so that my plugin wouldn't throw errors in the console the first time it fires up because admins haven't edited the config yet. However, you don't have to use SQLite. In fact, it's recommended to use MySQL. You just have to change "SQLite" to "MySQL" in the "database" section and fill in your database info.

I recon you had problems with SQLite not being supported by your server's Java setup. That's why I suggested you to use MySQL.
