### ISSUE TITLE
Issue with gamemode after disconnecting the server

### ISSUE THREAD

**Issue by AIphaDragon** [Prunt/RestrictedCreative#28]
Hello,
Recently, we have found an issue, that player's inventory from gm 1 remains the same in gm 0 when he leaves the server.
Here is a video to show the problem: https://www.youtube.com/watch?v=6hmMU9KYHFc&feature=youtu.be

We are looking forward to your answer

**Comment by Prunt** [comment]
Hi!

Are you sure you're not an OP, you don't have the bypass permission and you have separate inventories enabled in the config?

**Comment by AIphaDragon** [comment]
Hello,
Yes, we checked it out. Here we send your our config.yml pastebin to show all configurations.
https://pastebin.com/07fSkDuf

**Comment by AIphaDragon** [comment]
I think the problem is here: https://pastebin.com/PTVcpY1d. When you exit, the player's mode switches to survival. If you do not have time, I could try to correct the problem myself. Could you give a class to EventListener for testing this problem? Thank you in advance for your response.

**Comment by Prunt** [comment]
I'm very sorry for the late reply, I had to deal with exams.

What you brought up as a culprit isn't the problem here, as it's supposed to switch the player back to survival mode since the plugin doesn't save any inventories itself (for now). The problem is that for some reason the plugin isn't switching player's inventory.

Since I can't reproduce the problem myself (using Spigot 1.12.2 and RC v1.13.2), would you share your server version? Also, test if the problem persist when there aren't any other plugins installed to see if any of them might be interfering.

**Comment by Prunt** [comment]
I understand that you want to contribute to solving this issue, but I'd appreciate it if you'd stop sharing parts of my plugin's code publicly. Having said that, have you tried removing all other plugins to see if some them might be the cause as I suggested?

**Comment by AIphaDragon** [comment]
The plugin for multi-world forced the game mode, but it was corrected. The problem in the plugin itself is to limit the creative. Sorry that they threw off some of the code and did not answer for a long time.

**Comment by Prunt** [comment]
I understand that everything is working as intended now? Reopen the issue if you continue to have any problems.
