### ISSUE TITLE
[Suggestion] World Guard Regions

### ISSUE THREAD

**Issue by ShaneBolenback** [Prunt/RestrictedCreative#3]
I would suggest adding something, so you could limit the players to switch to creative mode ONLY in a certain region.

For example, I am having a building competition. I want to set up a large region players could use creative in, rather than anywhere in said world.

I hope to see this added soon :)

**Comment by Prunt** [comment]
Switching to creative mode could actually be done via WorldGuard game-mode flag only. Removing creative mode from players could be more problematic, because that would require a larger region outside the building competition boundaries and you'd have to disable teleporting out of it to force players go through the creative removal region. I believe that to better the solution I could also limit creative players to placing blocks/items only in certain regions.

**Comment by Prunt** [comment]
Added in v1.8.0.
