### ISSUE TITLE
Glitch 

### ISSUE THREAD

**Issue by EvilSlime** [Prunt/RestrictedCreative#32]
If I restart my server players in GMC will keep the GMC inv in GMS and their old GMS inv will be gone. Is there anyway you can fix this?

**Comment by Prunt** [comment]
I tested it with the latest RestrictedCreative version and Spigot 1.12.2. Creative inventory was removed from creative players on restart as they should.

What versions are you using? Do you have any other plugins installed?

**Comment by EvilSlime** [comment]
PaperSpigot 1.8.8

**Comment by EvilSlime** [comment]
0 errors, but I have 91 plugins installed.

**Comment by Prunt** [comment]
Can you test if this happens without any other plugins as well? There have been some problems with multiworld plugins, check out #28.

**Comment by EvilSlime** [comment]
It's not multiversecore I'll check the other suggestion now.

**Comment by EvilSlime** [comment]
Without any plugins I get the error: https://pastebin.com/X1z1X9kn

**Comment by EvilSlime** [comment]
It is one of my plugins but how could that even be possible...

**Comment by Prunt** [comment]
> Without any plugins I get the error: https://pastebin.com/X1z1X9kn

This is because ProtocolLib isn't installed, nothing to worry about.

> It is one of my plugins but how could that even be possible... http://prntscr.com/k5n32n

Well, it's probably a plugin that does something with players inventories on server shutdown.
To find out what plugin does that:

1. Remove half of your plugins (43 the first time, 22 the second etc, obviously keep RestrictedCreative).
2. Test to see if you removed the plugin at fault.
  2.2. If the bug persists, the plugin at fault is still installed and go back to step one.
  2.1. If the bug disappears, you removed the plugin that was causing it. Switch out the remaining plugins with the ones you removed and go back to step one.

**Comment by EvilSlime** [comment]
Okey so I tested it and it seems to be because PrinterMode is there any way you can fix this or do I have to contact them?

**Comment by Prunt** [comment]
Why would players even be online when world gets saved? That doesn't happen in regular Spigot, world always gets saved last. I switch players back to survival because I don't save any inventories to the database (this feature comes in 2.0). If I didn't put them back to survival, they'd lose their survival inventory.

**Comment by Prunt** [comment]
I'll close this for now. Feel free to reopen when needed.
