### ISSUE TITLE
[Possible Bug] RestrictedCreative conflicting with AutoReconnect.

### ISSUE THREAD

**Issue by DarkKingKaan** [Prunt/RestrictedCreative#91]
I use an Auto-Reconnect plugin on my server, so people don't have to disconnect on server restart. This puts them in a "frozen" world and tries to connect them back after rebooting. But there is one small problem.

The plugin tries to connect you back to the server, but RestrictedCreative is still loading blocks from the database. This results in a kick from the server and players get stuck on the empty world still waiting to be connected, which never happens.

I have tried migrating to MySQL database in the hope it will load faster with little to no luck. One simple fix would be to load the data from the database before the players are actually able to connect, instead of kicking them and causing issues.

If you have another idea on how to handle this issue, please let me know. Could this also be an issue on their side?

Thank you in advance for your answer.

**Comment by hankur** [comment]
1. You can allow players to connect to the server while blocks are still loading, you can find the option in the config. This will leave blocks that aren't loaded yet vulnerable for destruction, though.
2. Since the block loading is async and async operations can't run until the server itself is up and running, I can't do that before players can connect. Therefore, I must technically kick them while the database is still loading.
3. If the auto-reconnect plugin would be built so that it will try connecting the players again after a kick, then this wouldn't be an issue. So yes, there's something they can improve as well.

**Comment by DarkKingKaan** [comment]
Thank you. I will try the first option. I will also notify the other plugin developer.
